#!/bin/bash
dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
python make_portable.py /home/simon/devel/eg_emdw/cmake-build-debug/src/eg_ksat ./eg_ksat -l ../../emdw/build/src/libemdw.so -l ../../gLinear/build/Linux-Release-x86_64/libgLinear.so -l ../../patrecII/build/Linux-Release-x86_64/lib/libpatrecII.so -s 