#!/bin/bash

#--------------------------------------------------
# I might be a symlink, so here is my root dwelling
#--------------------------------------------------

#From https://stackoverflow.com/a/246128
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" 
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

#--------------------------------------------------
# Hey linker, also look here for .so files
#--------------------------------------------------

#From https://stackoverflow.com/a/37558191
export LD_LIBRARY_PATH=$DIR/bin:$LD_LIBRARY_PATH

#--------------------------------------------------
# Finally, hey Linux, run this binary please
#--------------------------------------------------

"$DIR/bin/run_purge_and_merge" "$@"
